name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        toolset: [MSVC]
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build
      shell: cmd
      run: msbuild Seth.sln /p:Platform=x86 /p:Configuration=${{ matrix.configuration }} ${{ env.toolset }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Seth - ${{ matrix.configuration }}
        path: ${{ matrix.configuration }}\Seth.dll
